apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: integratorengine
build:
  artifacts:
  - image: yogeshwarmahalle/integratorengine
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: base
  manifests:
    kustomize:
      paths:
      - k8s/base
- name: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
- name: oat
  manifests:
    kustomize:
      paths:
      - k8s/overlays/oat
- name: prod
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
- name: uat
  manifests:
    kustomize:
      paths:
      - k8s/overlays/uat
