apiVersion: v1
data:
  balinqProcessor.groovy: |+
    import org.apache.camel.Exchange;
    import org.apache.camel.Processor;


    public class balinqProcessor implements Processor {

        public void process(Exchange exchange) throws Exception {

            println "*******************************************************"
            println "******** I am from balinqProcessor version-1 **********"
            println "*******************************************************"

            String contentType = exchange.getIn().getHeader(Exchange.CONTENT_TYPE, String.class);
            String path = exchange.getIn().getHeader(Exchange.HTTP_URI, String.class);
            //path = path.substring(path.lastIndexOf("/"));

            exchange.getOut().setHeader(Exchange.CONTENT_TYPE, contentType + "; charset=UTF-8");
            exchange.getOut().setHeader("PATH", path);
            exchange.getOut().setBody("Response from Balance Inquiry.");
        }
    }

  balinqRouter.groovy: |
    import org.apache.camel.*
    import org.apache.camel.impl.*
    import org.apache.camel.builder.*


    public class balinqRouter extends RouteBuilder {

        def void configure() {

            from("direct://balinq-earmark").routeId("balinqRouter-balinq-earmark")
                .log(LoggingLevel.INFO, "Request received in Balance Inquiry : #{body}")
                .process("balinqProcessor")
                //.transform().constant("Response from Balance Inquiry")
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: configmap-balinq-integration
