apiVersion: v1
data:
  accpostProcessor.groovy: |+
    import org.apache.camel.Exchange;
    import org.apache.camel.Processor;


    public class accpostProcessor implements Processor {

        public void process(Exchange exchange) throws Exception {

            println "********************************************************"
            println "******** I am from accpostProcessor version-1 **********"
            println "********************************************************"

            String contentType = exchange.getIn().getHeader(Exchange.CONTENT_TYPE, String.class);
            String path = exchange.getIn().getHeader(Exchange.HTTP_URI, String.class);
            //path = path.substring(path.lastIndexOf("/"));

            exchange.getOut().setHeader(Exchange.CONTENT_TYPE, contentType + "; charset=UTF-8");
            exchange.getOut().setHeader("PATH", path);
            exchange.getOut().setBody("Response from Account Posting.");
        }
    }

  accpostRouter.groovy: |
    import org.apache.camel.*
    import org.apache.camel.impl.*
    import org.apache.camel.builder.*


    public class accpostRouter extends RouteBuilder {

        def void configure() {

            from("direct://accpost-pnp").routeId("accpostRouter-accpost-pnp")
                .log(LoggingLevel.INFO, "Request received in Account Posting : #{body}")
                .process("accpostProcessor")
                //.transform().constant("Response from Account Posting")
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: configmap-accpost-integration
