apiVersion: v1
data:
  GlobalProcessor.groovy: |
    import org.apache.camel.Exchange;
    import org.apache.camel.Processor;


    public class GlobalProcessor implements Processor {

        public void process(Exchange exchange) throws Exception {

            String contentType = exchange.getIn().getHeader(Exchange.CONTENT_TYPE, String.class);
            String path = exchange.getIn().getHeader(Exchange.HTTP_URI, String.class);
            //path = path.substring(path.lastIndexOf("/"));

            //assertEquals(Exchange.CONTENT_TYPE, contentType, "Get a wrong content type");
            // assert camel http header
            String charsetEncoding = exchange.getIn().getHeader(Exchange.HTTP_CHARACTER_ENCODING, String.class);
            //assertEquals(charsetEncoding, "Get a wrong charset name from the message header", "UTF-8");
            // assert exchange charset
            //assertEquals(exchange.getProperty(Exchange.CHARSET_NAME), "Get a wrong charset naem from the exchange property", "UTF-8");
            exchange.getOut().setHeader(Exchange.CONTENT_TYPE, contentType + "; charset=UTF-8");
            exchange.getOut().setHeader("PATH", path);
            exchange.getOut().setBody("Response from GlobalProcessor. ${exchange.getIn().getBody().getAt('text')}");

        }
    }
  GlobalRouter.groovy: |2

    //@Grab('org.apache.camel.springboot:camel-spring-boot-starter:3.7.0')

    import org.apache.camel.*
    import org.apache.camel.impl.*
    import org.apache.camel.builder.*
    import org.apache.camel.model.rest.*
    import org.springframework.http.*


    class GlobalRouter extends RouteBuilder {
        def void configure() {

            from("direct://fusion-pil-status").routeId("GlobalGroovyRouter-fusion-pil-status")
                .log(LoggingLevel.INFO, "Request received in GlobalRouter : ${body()}")
                .process("GlobalProcessor")
                //.transform().constant("Response from GlobalRouter")

        }
    }
  GlobalRouter.xml: |
    <routes id="GlobalXMLRouter" xmlns="http://camel.apache.org/schema/spring">

      <route id="GlobalXMLRouter-hello">
        <from uri="direct:xmlhello"/>
        <log message="Got ${body}"/>
        <transform>
          <constant>Hello World</constant>
        </transform>
      </route>
      <route id="GlobalXMLRouter-bye">
        <from uri="direct:xmlbye"/>
        <transform>
          <constant>Bye World</constant>
        </transform>
      </route>

    </routes>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: configmap-global-integration
